### ISSUE TITLE
Unexpected end of line

### ISSUE THREAD

**Issue by Yimura** [Akke/BotDocs#6]
https://github.com/Akke/BotDocs/blob/fc6b465bb4a9ae271f35bb941b51bee34c9a50f5/src/components/menu/_menu.module.sass#L37

**Comment by Akke** [comment]
This has been fixed in the [latest commit](https://github.com/Akke/BotDocs/commit/ebba4427f3afcf426e5be14c258ff0ddf14f0e1e).

It's worth mentioning that this seem to be very specific to what environment that tries to compile the sass files, on Windows 10 with Node 16.1.0 it runs completely fine - in other words I can not reproduce this on my end, but the error is clearly visible if you put the given syntax through a verifier like [sassmeister](https://www.sassmeister.com/).
